import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";

const inter = Fredoka({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: "Clima ",
  description: "Generated by create next app",
  icons: { icon: "/Assets/favicon.ico" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.variable}>{children}</body>
    </html>
  );
}
